### ISSUE TITLE
HashMap's and StringBuilder's generate incorrectly

### ISSUE THREAD

**Issue by jdanbrown** [codahale/jerkson#12]
scala> generate(scala.collection.immutable.HashMap(1->2))
res61: String = {"1":2}

scala> generate(scala.collection.mutable.HashMap(1->2))
res62: String = [{"_1":1,"_2":2}]

scala> generate(scala.collection.mutable.LinkedHashMap(1->2))
res63: String = [{"_1":1,"_2":2}]

scala> generate("foo")
res32: String = "foo"

scala> generate(new scala.collection.mutable.StringBuilder("foo"))
res31: String = ["f","o","o"]

I'm also submitting a pull request containing a comprehensive set of tests for the scala-2.8.1 collections (http://www.scala-lang.org/docu/files/collections-api/collections_2.html), including the three above that fail.

**Comment by codahale** [comment]
Fixed, thanks. Working on support for a lot of other types, too.
