### ISSUE TITLE
Serialization of None Incorrect When In Case Class

### ISSUE THREAD

**Issue by lambdaknight** [codahale/jerkson#21]
``` scala
case class Foo(a: Option[String])
val json = generate(Foo(None))
```

In this code _json_ is set to `{}` rather than `{"a":null}`.

It should be as simple as adding this code to CaseClassSerializer.scala:32:

``` scala
else {
  json.writeFieldName(methodOpt.map {_.getName}.getOrElse(field.getName))
  provider.getNullValueSerializer.serialize(null, json, provider)
}
```

**Comment by codahale** [comment]
Fight it out with @tc: https://github.com/codahale/jerkson/issues/6

**Comment by lambdaknight** [comment]
Is that the canonical way of serializing Option[_]?  It seems like it would violate the principle of least surprise to have a None show up as just not being there.

**Comment by codahale** [comment]
There is no canonical way of serializing Scala types to JSON values. This is one of many.

As far as things being surprising, mapping a trinary value (`"blah"`, `null`, or a field which doesn't exist) to a binary value (`Some("blah")`, `None`) will always involve collision and thus "surprise."
