### ISSUE TITLE
How to work with jerkson and other jackson modules

### ISSUE THREAD

**Issue by manuelbernhardt** [codahale/jerkson#26]
We have a de/serializer for BSON ObjectId's registered like this:

```
val mapper = new ObjectMapper
val module: SimpleModule = new SimpleModule("foo", Version.unknownVersion())
module.addSerializer(classOf[ObjectId], new ObjectIdSerializer)
module.addDeserializer(classOf[ObjectId], new ObjectIdDeserializer)
mapper.registerModule(module)
```

But it does not seem to be picked up when serializing a case class that has an ObjectId using `generate`. Could it be that for this to work, the de/serializers need to be registered against the same ObjectMapper than the one jerkson uses? If yes, how to get a hold on them?

Thanks,

manuel

**Comment by manuelbernhardt** [comment]
It looks as tough using the same ObjectMapper as jerkson does the trick. For a quick&dirty hack see https://github.com/manuelbernhardt/jerkson/commit/8504352ee4154b8e2deef2914fdd233a8afaafe6.

It would be nice to get access to this in a clean way.

**Comment by codahale** [comment]
So the `Json` object is just a convenient singleton. All it does is extend the `Json` trait which has protected versions of everything you want:

``` scala
object MyJson extends Json {
   mapper.addSerializer(etc)
}
```

**Comment by manuelbernhardt** [comment]
This way of accessing the mapper doesn't really work for me because I need access to the same mapper against which the ScalaModule has been registered to, otherwise custom serialization of objects that start within the context of the ScalaModule (e.g. serializing an ObjectId inside of a scala.Option) won't work.

Using the method described above I get a new Mapper instance:

```
direct access: org.codehaus.jackson.map.ObjectMapper@36293f1d
MyJson access: org.codehaus.jackson.map.ObjectMapper@6e7eca16
```

Perhaps a getter for the mapper on the Json singleton would be a clean way?

Thanks!

**Comment by codahale** [comment]
It doesn't need to be the same instance as the instance in the `Json` object, it just needs to be initialized the same way, which it is.

**Comment by manuelbernhardt** [comment]
Mea culpa. It not only needs to be initialized, but also used (I had some imports to `Json` still hanging around).

**Comment by scharris** [comment]
I hate to pile on to an old closed issue, I'm not sure where else to ask about this though.  I'm trying to follow the advice given here with the "MyJson" object def above, to customize the Jackson object mapper,  and having a bit of a problem.  I'm trying to get types to show up in the output.  Here's my attempt:

```
sealed abstract class A
case class B(s: String) extends A
case class C(s: String) extends A

object Json extends com.codahale.jerkson.Json {
  mapper.enableDefaultTypingAsProperty(org.codehaus.jackson.map.ObjectMapper.DefaultTyping.NON_FINAL, "@class")
}

Json.generate(B("hello"))
```

> {"s":"hello"} // no type written (?)

It seems I either don't understand Jackson (quite possible) or my changes to the mapper aren't being seen?
Any advice would be much appreciated.
