### ISSUE TITLE
Please update to Scala 2.9.1

### ISSUE THREAD

**Issue by ngocdaothanh** [codahale/jerkson#29]
It has just been released!
http://www.scala-lang.org/node/10780

**Comment by codahale** [comment]
I will eventually, but I should note that `jerkson_2.9.0-1` should be binary compatible with Scala 2.9.1. If it's not, they've broken something.

**Comment by ngocdaothanh** [comment]
Ah, I see.

Setting like this in build.sbt is OK:
libraryDependencies += "com.codahale" % "jerkson_2.9.0-1" % "0.4.0"

Many thanks.

**Comment by codahale** [comment]
Closed by 4359e78f75d5e907022051ee5c2bc114afa807af.
