### ISSUE TITLE
Parse from a Class[T] instead of a Manifest[T]

### ISSUE THREAD

**Issue by acruise** [codahale/jerkson#32]
It'd sure be nice!

**Comment by codahale** [comment]
Sigh. These were related.

d592703821bca2cf3178a949a6779a87f1e5f650
5d47ca4b41af158f52e321c29befe0eca76ab730

But Scala 2.8.1 doesn't have `scala.reflect.Manifest`, and if it did you'd just do `Manifest.classType(classOf[Blah])` yourself.

So I think the solution to this one is to upgrade to 2.9.1.
