### ISSUE TITLE
EitherDeserializer is "weird"

### ISSUE THREAD

**Issue by jasongilanfarr** [codahale/jerkson#36]
Currently, the deserializer assumes the value is a Left(_) and simply surrounds it with try {} catch { Right(_) }.

This goes against the common use of Either (as documented in the scaladocs):
Represents a value of one of two possible types (a disjoint union). The data constructors Left and Right represent the two possible values. The Either type is often used as an alternative to Option where Left represents failure (by convention) and Right is akin to Some.

The most common case is: Either[Throwable, T] so this deserializer is essentially backwards from the common case; however, I think it would be good to deserialize it using some kind of meta-data to ensure that you get the expected Left/Right.

**Comment by codahale** [comment]
I'm using it as a generic union type, since Jackson has no built-in serialization support for exceptions.

And as far as adding metadata: no.

**Comment by jasongilanfarr** [comment]
Even still, Right is the "common" side of the Union.
