### ISSUE TITLE
Upgrade to Jackson 2

### ISSUE THREAD

**Issue by benmccann** [codahale/jerkson#50]
I'd love to see Jerkson upgrade to Jackson 2.0.

**Comment by ghost** [comment]
+1

**Comment by benmccann** [comment]
Btw, see https://github.com/FasterXML/jackson-module-scala

**Comment by JorritPosthuma** [comment]
Or this one: https://github.com/wg/jacks

**Comment by imikushin** [comment]
I've just ported Jerkson to Jackson 2 and submitted a pull request: https://github.com/codahale/jerkson/pull/60 
Enjoy! And vote ;)

**Comment by codahale** [comment]
Closed via #60.
