### ISSUE TITLE
No update since 6 months. Jerkson is a dead end, isn't it?

### ISSUE THREAD

**Issue by FaKod** [codahale/jerkson#56]
Yammer kicked Scala. So, do we see any efforts here?

**Comment by JorritPosthuma** [comment]
You can look at Jackson's own Scala extention: https://github.com/FasterXML/jackson-module-scala, or another that is already up-to-date to Jackson 2.0: https://github.com/wg/jacks

**Comment by codahale** [comment]
Neither JSON nor Scala 2.9 have changed dramatically in the past 6 months.

Jerkson is in a stable state, it does everything I want it to, and I don't get paid to shave yaks.

If you don't like this, feel free not to use this library.

**Comment by FaKod** [comment]
So you will habe a look to all the issues and pull requests? (Though we all are free not to use things and did not get payed for our open source efforts )

**Comment by codahale** [comment]
I've looked at each and every one.
