### ISSUE TITLE
Make auto-close optional

### ISSUE THREAD

**Issue by collinvandyck** [codahale/jerkson#7]
When a writer is supplied to Jerkson, it passes it off to Jackson generator configured to auto-close the supplied writer.  It would be nice to be able to turn that off.  When I'm working with a very large JSON file parsing it via the Jackson streaming API, it's expensive to open up a writer each time I need to write data to a particular file.  To get around this, I am currently:

val sw = new StringWriter
Json.parse(obj, sw)
val writer = getCachedWriter(file)
writer.write(sw.toString)
writer.flush

**Comment by codahale** [comment]
Yeah, that's not good. Right now you can work around that like this:

``` scala
import org.codehaus.jackson.map.{MappingJsonFactory, ObjectMapper}
import org.codehaus.jackson.{JsonGenerator, JsonParser => JacksonParser}

object NonClosingJson extends Parser with Generator {
  protected val mapper = new ObjectMapper
  mapper.registerModule(new ScalaModule)

  protected val factory = new MappingJsonFactory(mapper)
  factory.enable(JsonGenerator.Feature.AUTO_CLOSE_JSON_CONTENT)
  // NO YUO
  factory.disable(JsonGenerator.Feature.AUTO_CLOSE_TARGET)
  factory.enable(JsonGenerator.Feature.QUOTE_FIELD_NAMES)
  factory.enable(JacksonParser.Feature.ALLOW_COMMENTS)
  factory.enable(JacksonParser.Feature.AUTO_CLOSE_SOURCE)
}
```

But I really should extract this out into a base class that the `Json` object can then extend.

**Comment by codahale** [comment]
(I always forget to mention the issue number in the commit.)

Fixed in 40c2c820287550267003a3e3206a077c06fc526d.

**Comment by codahale** [comment]
Now you can just do this:

``` scala
object NonClosingJson extends Json {
  factory.disable(JsonGenerator.Feature.AUTO_CLOSE_TARGET)
}
```

**Comment by collinvandyck** [comment]
Thanks, that's really clean.
