### ISSUE TITLE
What's your proposed alternative to Jerkson

### ISSUE THREAD

**Issue by ngocdaothanh** [codahale/jerkson#77]
I've been using Jerson in my web framework:
http://ngocdaothanh.github.com/xitrum/

Now that Jerkson is abandoned, what's your proposed alternative?

Thanks.

**Comment by imikushin** [comment]
I've been using [salat](https://github.com/novus/salat) for a while now. The project is active.

**Comment by chiappone** [comment]
check out json4s

**Comment by ngocdaothanh** [comment]
Thanks.
I decided to use JSON4S.

**Comment by nbauernfeind** [comment]
Don't forget about FasterXML's scala plugin for jackson: jackson-module-scala. It works extremely well.
