### ISSUE TITLE
Optional _typeHint generation

### ISSUE THREAD

**Issue by gzoller** [codahale/jerkson#9]
Idea shameless stolen from the Salat project... it would be cool to have a switch to optionally turn on generation of a _typeHint parameter in the generated Json, and have deserializer use the hint.

You could have something like this:

trait Stuff
case class Car extends Stuff
case class Truck extends Stuff
case class Train( val numCars:Int) extends Stuff
case class MyStuff( val name:String, val favorites:List[Stuff])

val ms = MyStuff("Greg", List(Car(), Train(5))

Currently I'm not sure how Jerkson would know what to do with this.  It might generate something like this:

{"name":"Greg","favorites":[{},{"numCars":5}]}

Ok, but how would it deserialize this?  It has no way to know that {} is actually a Car object...or is it a Truck object?

Salat's _typeHint solves this by generating something like:

{"_typeHint":"MyStuff","name":"Greg","favorites":[{"_typeHint":"Car"},{"_typeHint":"Train","numCars":5}]}

If you've got something in the deserializer to catch and read the type hint you know exactly what kind of object to create.

Of course this would be some kind of config parameter so you wouldn't get the hints unless you wanted them.

**Comment by codahale** [comment]
I'd rather not have this sort of thing in Jerkson, sorry.

**Comment by gzoller** [comment]
No worries.  It would get away from the clean design you've got here.

El domingo 8 de mayo de 2011, codahale
reply@reply.github.com
escribió:

**Comment by gzoller** [comment]
Hi Coda,

I've been fiddling with Jerkson and the concepts borrowed from Salat that
attempt to counteract Scala's penchant for erasing the Enumeration type
information needed to property deserialize an Enumeration from json.

I think I've boiled the (extensive) Salat stuff down to one small class,
Seer, that uses scalap to inspect the class file and infer the intended type
of the Enumeration.  T'wasn't easy!

The one limitation is that the Enumeration can't be stand-alone in the
json--it must be a data member of a case class to work.

My fork of the Jerkson code is here: https://github.com/gzoller/jerkson

To use it just define something like the code below and use generate/parse
as normal:

case class Person(age:Int, hero:Matrix.Value)
object Matrix extends Enumeration {
    val Neo, Morpheus = Value
}

val p = Person(30, Matrix.Morpheus)
val js = generate(p)
val p2 = parse[Person](js)

This does what I need it to in terms of parsing Enumerations.  Of course
you're welcome to it if you want it back as part of Jerkson.  Granted the
scalap thing is a little different and unfortunate that its needed, but its
likely the only way to get the job done w/o polluting the json with hints.

Best regards,
Greg
